### ISSUE TITLE
sh: 1: cls: not found Traceback (most recent call last):  

### ISSUE THREAD

**Issue by Elektrobotcdp** [billythegoat356/pystyle#13]
sh: 1: cls: not found
Traceback (most recent call last):
  File "/home/bdv/Desktop/Netflixer-CHECKER/main.py", line 150, in <module>
    banner()

**Comment by loTus04** [comment]
The script detected you are using windows, so it's using batch
But it looks like you are using bash, that's why the 'cls' command doesn't work, try replacing 'cls' by 'clear' or doing an alias

**Comment by Elektrobotcdp** [comment]
am using parrot os

**Comment by KlamkaDoDrzwi** [comment]
cs
